/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.1
 * Generated at: 2022-08-02 07:05:26 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.member;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class login_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(4);
    _jspx_dependants.put("jar:file:/C:/java/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/pension_se/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("jar:file:/C:/java/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/pension_se/WEB-INF/lib/jstl-1.2.jar!/META-INF/fmt.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1657678760970L));
    _jspx_dependants.put("jar:file:/C:/java/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/pension_se/WEB-INF/lib/jstl-1.2.jar!/META-INF/fn.tld", Long.valueOf(1153352682000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fimport_0026_005furl_005fnobody;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fimport_0026_005furl_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fimport_0026_005furl_005fnobody.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write(" \r\n");
      out.write("\r\n");
      out.write(" <!-- 복사폼.jsp -->    \r\n");
      if (_jspx_meth_c_005fimport_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("<style>\r\n");
      out.write("#section{\r\n");
      out.write("\twidth:1100px;\r\n");
      out.write("\theight:500px;\r\n");
      out.write("\tmargin:auto;\r\n");
      out.write("\ttext-align:center;\r\n");
      out.write("}\r\n");
      out.write("#section input[type=text] {\r\n");
      out.write("\tmargin-top:50px;\r\n");
      out.write("\twidth: 300px;\r\n");
      out.write("\theight: 40px;\r\n");
      out.write("\tborder: 1px solid purple;\r\n");
      out.write("\toutline: none;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#section input[type=password] {\r\n");
      out.write("\twidth: 300px;\r\n");
      out.write("\theight: 40px;\r\n");
      out.write("\tborder: 1px solid purple;\r\n");
      out.write("\toutline: none;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#section input[type=submit] {\r\n");
      out.write("\twidth: 300px;\r\n");
      out.write("\theight: 40px;\r\n");
      out.write("\tborder: 1px solid purple;\r\n");
      out.write("\toutline: none;\r\n");
      out.write("\tbackground: purple;\r\n");
      out.write("\tcolor: white;\r\n");
      out.write("\tfont-size: 20px;\r\n");
      out.write("}\r\n");
      out.write("#loginSearch .btn{\r\n");
      out.write("\twidth:300px;\r\n");
      out.write("\theight: 40px;\r\n");
      out.write("\tborder: 1px solid green;\r\n");
      out.write("\toutline:none;\r\n");
      out.write("\tfont-size:20px;\r\n");
      out.write("\tmargin-top:15px;\r\n");
      out.write("\tmargin-left:20px;\r\n");
      out.write("}\r\n");
      out.write("#useridSearch, #pwdSearch{\r\n");
      out.write("\tmargin-top:20px;\r\n");
      out.write("\tdisplay:none;\r\n");
      out.write("}\r\n");
      out.write("#search{\r\n");
      out.write("\tmargin-top:15px;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("\r\n");
      out.write("$(function(){\r\n");
      out.write("\t\r\n");
      out.write("\t$(\".btn\").eq(0).click(function(){\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t$(\"#useridSearch\").css(\"display\",\"block\");\r\n");
      out.write("\t\t$(\"#pwdSearch\").css(\"display\",\"none\");\r\n");
      out.write("\t\t$(\"#pwdSearch input[name=userid]\").val(\"\");\r\n");
      out.write("\t\t$(\"#pwdSearch input[name=name]\").val(\"\");\r\n");
      out.write("\t\t$(\"#pwdSearch input[name=phone]\").val(\"\");\r\n");
      out.write("\t});\r\n");
      out.write("\t\r\n");
      out.write("\t$(\".btn\").eq(1).click(function(){\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t$(\"#useridSearch\").css(\"display\",\"none\");\r\n");
      out.write("\t\t$(\"#pwdSearch\").css(\"display\",\"block\");\r\n");
      out.write("\t\t$(\"#useridSearch input[name=name]\").val(\"\");\r\n");
      out.write("\t\t$(\"#useridSearch input[name=phone]\").val(\"\");\r\n");
      out.write("\t});\r\n");
      out.write("});\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("function idSearch(){\r\n");
      out.write("\t\r\n");
      out.write("\tvar name = document.pkc1.name.value;\r\n");
      out.write("\tvar phone = document.pkc1.phone.value;\r\n");
      out.write("\t\r\n");
      out.write("\tvar search = new XMLHttpRequest();\r\n");
      out.write("\tsearch.open(\"get\",\"member_useridsearch.jsp?name=\"+name+\"&phone=\"+phone);\r\n");
      out.write("\tsearch.send();\r\n");
      out.write("\t\r\n");
      out.write("\tsearch.onreadystatechange = function(){\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tif(search.readyState == 4){\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tvar id = search.responseText.trim();\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tif(id==\"1\"){\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\talert(\"정보가 틀립니다\");\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\telse\r\n");
      out.write("\t\t\t\tdocument.getElementById(\"searchinn\").innerText=\"당신의 아이디는 \"+id+\" 입니다\";\r\n");
      out.write("\t\t}\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("}\r\n");
      out.write("function dbpwdSearch(){\r\n");
      out.write("\t\r\n");
      out.write("\tvar userid = document.pkc2.userid.value;\r\n");
      out.write("\tvar name = document.pkc2.name.value;\r\n");
      out.write("\tvar phone = document.pkc2.phone.value;\r\n");
      out.write("\t\r\n");
      out.write("\tvar sse = new XMLHttpRequest();\r\n");
      out.write("\tsse.open(\"get\",\"member_pwdsearch.jsp?userid=\"+userid+\"&name=\"+name+\"&phone=\"+phone);\r\n");
      out.write("\tsse.send();\r\n");
      out.write("\t\r\n");
      out.write("\tsse.onreadystatechange = function(){\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tif(sse.readyState == 4){\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tvar pp = sse.responseText.trim();\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tif(pp == \"1\")\r\n");
      out.write("\t\t\t\talert(\"정보가 틀립니다\");\t\t\t\r\n");
      out.write("\t\t\telse\r\n");
      out.write("\t\t\t\tdocument.getElementById(\"searchinn\").innerText=\"당신의 비밀번호는 \"+pp+\" 입니다\";\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("   \t   \r\n");
      out.write("   <div id=\"section\">\r\n");
      out.write("   \r\n");
      out.write("   \t<form method=\"post\" action=\"../member/login_ok.jsp\">\r\n");
      out.write("   \t\r\n");
      out.write("   \t<input type=\"text\" name=\"userid\" placeholder=\"아이디입력\"><p>\r\n");
      out.write("   \t<input type=\"password\" name=\"pwd\" placeholder=\"비밀번호 입력\"><p>\r\n");
      out.write("   \t<input type=\"submit\" value=\"로그인\">\r\n");
      out.write("   \t\r\n");
      out.write("   \t</form>\r\n");
      out.write("   <div id=\"loginSearch\">\r\n");
      out.write("  \t<span class=\"btn\">아이디찾기</span>\r\n");
      out.write("  \t<span class=\"btn\">비밀번호 찾기</span>\r\n");
      out.write("   </div>\r\n");
      out.write("   \r\n");
      out.write("   <span id=\"searchinn\" style=\"font-size:12px;\"></span>\r\n");
      out.write("   \r\n");
      out.write("   <div id=\"useridSearch\" >\r\n");
      out.write("   <form name=\"pkc1\">\r\n");
      out.write("   \t<input type=\"text\" name=\"name\"  placeholder=\"이름입력\"><p>\r\n");
      out.write("   \t<input type=\"text\" name=\"phone\"  placeholder=\"전화번호 입력\"><p>\r\n");
      out.write("   \t<input type=\"button\" onclick=\"idSearch()\" value=\"아이디찾기\">   <p>\r\n");
      out.write("   </form>\r\n");
      out.write("   </div>\r\n");
      out.write("   \r\n");
      out.write("   <div id=\"pwdSearch\">\r\n");
      out.write("   \r\n");
      out.write("   <form name=\"pkc2\">\r\n");
      out.write("   <input type=\"text\" name=\"userid\"  placeholder=\"아이디입력\"><p>\r\n");
      out.write("   <input type=\"text\" name=\"name\"  placeholder=\"이름입력\"><p>\r\n");
      out.write("   <input type=\"text\" name=\"phone\"  placeholder=\"전화번호 입력\"><p>\r\n");
      out.write("   <input type=\"button\" onclick=\"dbpwdSearch()\" value=\"비밀번호 찾기\"><p>\r\n");
      out.write("   </form>\r\n");
      out.write("   </div>\r\n");
      out.write("   \r\n");
      out.write("   \r\n");
      out.write("   \r\n");
      out.write("   </div>\r\n");
      out.write("   \r\n");
      out.write("   \r\n");
      out.write("   \r\n");
      out.write("   \r\n");
      out.write("   \r\n");
      out.write("   \r\n");
      out.write("   \r\n");
      out.write("   \r\n");
      out.write("   \r\n");
      out.write("   \r\n");
      out.write("   \r\n");
      out.write("   \r\n");
      out.write("   \r\n");
      out.write("   \r\n");
      out.write("   \r\n");
      out.write("   \r\n");
      out.write("   \r\n");
      out.write("   \r\n");
      out.write("   \r\n");
      out.write("   </div>\r\n");
      out.write("   \t\r\n");
      out.write("   \t\r\n");
      out.write("   \t\r\n");
      if (_jspx_meth_c_005fimport_005f1(_jspx_page_context))
        return;
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fimport_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:import
    org.apache.taglibs.standard.tag.rt.core.ImportTag _jspx_th_c_005fimport_005f0 = (org.apache.taglibs.standard.tag.rt.core.ImportTag) _005fjspx_005ftagPool_005fc_005fimport_0026_005furl_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.ImportTag.class);
    boolean _jspx_th_c_005fimport_005f0_reused = false;
    try {
      _jspx_th_c_005fimport_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fimport_005f0.setParent(null);
      // /member/login.jsp(7,0) name = url type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fimport_005f0.setUrl("../top.jsp");
      int[] _jspx_push_body_count_c_005fimport_005f0 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fimport_005f0 = _jspx_th_c_005fimport_005f0.doStartTag();
        if (_jspx_th_c_005fimport_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fimport_005f0[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fimport_005f0.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fimport_005f0.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fimport_0026_005furl_005fnobody.reuse(_jspx_th_c_005fimport_005f0);
      _jspx_th_c_005fimport_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fimport_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fimport_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fimport_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:import
    org.apache.taglibs.standard.tag.rt.core.ImportTag _jspx_th_c_005fimport_005f1 = (org.apache.taglibs.standard.tag.rt.core.ImportTag) _005fjspx_005ftagPool_005fc_005fimport_0026_005furl_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.ImportTag.class);
    boolean _jspx_th_c_005fimport_005f1_reused = false;
    try {
      _jspx_th_c_005fimport_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fimport_005f1.setParent(null);
      // /member/login.jsp(196,0) name = url type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fimport_005f1.setUrl("../bottom.jsp");
      int[] _jspx_push_body_count_c_005fimport_005f1 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fimport_005f1 = _jspx_th_c_005fimport_005f1.doStartTag();
        if (_jspx_th_c_005fimport_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fimport_005f1[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fimport_005f1.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fimport_005f1.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fimport_0026_005furl_005fnobody.reuse(_jspx_th_c_005fimport_005f1);
      _jspx_th_c_005fimport_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fimport_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fimport_005f1_reused);
    }
    return false;
  }
}
